name: Sync index.html with gh-pages

on:
  push:
    branches: ["main"]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history
      - name: Configure Git
        run: |
          git config user.email ${{secrets.USER_EMAIL}}
          git config user.name ${{secrets.USER_NAME}}
      - name: Push changes to gh-pages
        run: |
          git checkout gh-pages
          git checkout main -- index.html  # replace with the path to your file
          git commit -m "Sync index.html from main"
          git push origin gh-pages
